sudo: required
language: python
branches:
  only:
    - master
python:
  - "2.7"
# TODO This may help building xo packages
# cache:
#  directories:
#  - sugar-build

before_install:
  - "pip install flake8"
# TODO This may be needed to build xo packages
#  - "git clone git://github.com/sugarlabs/sugar-build.git"
#  - "cd sugar-build"
#  - "./osbuild pull"
#  - "./osbuild build"
#  - "cd activities/"

install: 
  - "git clone -b master https://github.com/sugarlabs/edit-fonts-activity.git EditFonts.activity"

script: 
  - "cd EditFonts.activity"
  - "flake8 --statistics  --ignore=E402 --exclude=defcon,extractor,fontTools,fontmake,robofab,ufo2ft,ufoLib,snippets ."
  - "cd .."
# TODO This may be needed to build xo packages
#  - "echo 'python activities/EditFonts.activity/setup.py dist_xo' | ./osbuild shell"

# TODO define this 
# after_success:
#  - "cd ~; ls -alFR"
  
# TODO Set this up to auto-deploy tagged commits to the github releases page
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#tags: true
